version: "3.7"

services:
  # users:
  # 	container_name: users
  # 	build:
  # 		context: ./services/users
  # 		dockerfile: Docker
  # 	ports:
  # 		- 5001:5000

  tesseract:
    #container_name: tesseract
    build:
      context: ./app/services/tesseract/
      dockerfile: Dockerfile
    volumes:
      - tesseract:/tesseract/model/traineddata

  recogniser:
    container_name: recogniser
    build:
      context: ./app/services/recogniser/
      dockerfile: Dockerfile
    # volumes:
    #   - type: bind
    #     source: ./app/services/tesseract/data/
    #     target: /recogniser/model/traineddata

  mobile_app:
    build:
      context: ./app/services/mobile_app/
      dockerfile: Dockerfile
    env_file: ./app/services/mobile_app/.env
    ports:
      - 19000:19000
      - 19001:19001

  nginx:
    container_name: nginx
    build:
      context: ./app/services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80

volumes:
  tesseract:
