version: "3.7"

services:

	users:
		container_name: users
		build:
			context: ./services/users
			dockerfile: Docker
		ports:
			- 5001:5000

	nginx:
		build:
			context: ./services/nginx
			dockerfile: Dockerfile
		restart: always
		ports:
			- 80:80
